### PR TITLE
Added minimum and maximum height for beacon range

### PR DESCRIPTION
**Pull request by Insane96**
[As specified on the wiki](https://minecraft.gamepedia.com/Beacon#Range) the beacon has a downward range equal to his horizontal range and an upward range equal to his horizontal range + 256.

### CODE REVIEW

**Comment by ephys** [comment]
Hi, thanks for your work :)

I can see the appeal for this but it should go behind a config option. I'd like to keep the current behavior the default one.

I can probably find the time to add that option and release somewhere next week.

**Comment by Insane96** [comment]
Uh ok. I'll wait for 'till next week

**Comment by Insane96** [comment]
If you want and you like it you can use my [Config code](https://github.com/Insane-96/VulcaniteMod/blob/master/common/net/insane96mcp/vulcanite/lib/Config.java)

**Comment by ephys** [comment]
Oh, thanks but I already have an annotation based configuration that I want to port to 1.12 :) 
https://github.com/Ephys/Utilitas/blob/1.10.x/src/main/java/be/ephys/utilitas/feature/entity_sensor/FeatureProximitySensor.java#L34

**Comment by Insane96** [comment]
Wow. That's cool

**Comment by ephys** [comment]
Here you go :) Added config options to match the options provided by https://github.com/Ephys/ConfigurableBeacons (both mods are useable independantly ofc).

I'll release the update either later today or tomorrow

**Pull request merged**
